version: "3"
services:
  playwright-tests:
    build:
      context: playwright
      dockerfile: Dockerfile
    ipc: host
    volumes:
      - ./playwright:/app/
      - playwright_node_modules:/app/node_modules
volumes:
  playwright_node_modules:
